language: node_js

services:
  - docker

before_install:
  - docker build -t node_proj_docker .
  - docker run -p 3000:3000 node_proj_docker:latest .
  - docker ps -a

script:
  - bundle exec rake test