language: node_js

services:
  - docker

before_install:
  - docker build .
  - docker build -t node_proj_docker .
  - docker run -d -p 3000:3000 node_proj_docker:latest .
  - docker ps -a

deploy:
  provider: heroku
  api_key: 6b59173f-1813-4d6e-8637-967ad18be361
  app: nodejsd